// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/orchestrator.proto

// Sati-Central Root Spine — Orchestrator gRPC Service
// Version: 1.0.0
//
// This file is the contract between the Go root-spine and every factory,
// control panel, and external agent. All fields are commented.
// Breaking changes require a filed proposal in proposals/.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_CreateFactory_FullMethodName         = "/sati.central.v1.Orchestrator/CreateFactory"
	Orchestrator_StopFactory_FullMethodName           = "/sati.central.v1.Orchestrator/StopFactory"
	Orchestrator_ListFactories_FullMethodName         = "/sati.central.v1.Orchestrator/ListFactories"
	Orchestrator_SubmitProposal_FullMethodName        = "/sati.central.v1.Orchestrator/SubmitProposal"
	Orchestrator_ApproveAction_FullMethodName         = "/sati.central.v1.Orchestrator/ApproveAction"
	Orchestrator_VetoAction_FullMethodName            = "/sati.central.v1.Orchestrator/VetoAction"
	Orchestrator_GetFitnessSnapshot_FullMethodName    = "/sati.central.v1.Orchestrator/GetFitnessSnapshot"
	Orchestrator_RegisterDomainMetrics_FullMethodName = "/sati.central.v1.Orchestrator/RegisterDomainMetrics"
	Orchestrator_GetDhammaContext_FullMethodName      = "/sati.central.v1.Orchestrator/GetDhammaContext"
	Orchestrator_WriteAnalystBriefing_FullMethodName  = "/sati.central.v1.Orchestrator/WriteAnalystBriefing"
	Orchestrator_ReadAnalystVerdict_FullMethodName    = "/sati.central.v1.Orchestrator/ReadAnalystVerdict"
	Orchestrator_ReportMetrics_FullMethodName         = "/sati.central.v1.Orchestrator/ReportMetrics"
	Orchestrator_CreateAssemblyLine_FullMethodName    = "/sati.central.v1.Orchestrator/CreateAssemblyLine"
	Orchestrator_GetAssemblyLineStatus_FullMethodName = "/sati.central.v1.Orchestrator/GetAssemblyLineStatus"
	Orchestrator_AdvanceLifecycle_FullMethodName      = "/sati.central.v1.Orchestrator/AdvanceLifecycle"
	Orchestrator_UpdateSkill_FullMethodName           = "/sati.central.v1.Orchestrator/UpdateSkill"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Orchestrator is the central control plane for Sati-Central.
// It manages factory lifecycles, the safety verification pipeline,
// the fitness vector, Dhamma context retrieval, and the analyst interface.
type OrchestratorClient interface {
	// CreateFactory instantiates and registers a new agent factory.
	// Returns the factory ID and initial fitness baseline.
	CreateFactory(ctx context.Context, in *FactoryRequest, opts ...grpc.CallOption) (*FactoryResponse, error)
	// StopFactory gracefully shuts down a running factory.
	// Waits for in-flight proposals to complete before stopping.
	StopFactory(ctx context.Context, in *FactoryID, opts ...grpc.CallOption) (*OperationStatus, error)
	// ListFactories returns all registered factories and their current status.
	ListFactories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FactoryList, error)
	// SubmitProposal submits an ActionProposal for safety verification.
	// Returns a stream of VerificationEvents as the proposal progresses
	// through: received → verifying → verdict → [gate_pending] → committed/vetoed.
	SubmitProposal(ctx context.Context, in *ActionProposal, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VerificationEvent], error)
	// ApproveAction signs a Translucent Gate approval for a security-adjacent proposal.
	// Requires a valid ApprovalSignature. Returns a MerkleProof for the committed leaf.
	ApproveAction(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*MerkleProof, error)
	// VetoAction issues a veto on a pending proposal.
	// May be called by the Analyst Droid or the human operator.
	VetoAction(ctx context.Context, in *VetoRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	// GetFitnessSnapshot returns the current global fitness vector state.
	// Equivalent to reading otel-snapshots/latest.json but via RPC.
	GetFitnessSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FitnessSnapshot, error)
	// RegisterDomainMetrics registers domain-specific fitness metric extensions.
	// Called by factories at startup to advertise their domain metrics.
	RegisterDomainMetrics(ctx context.Context, in *DomainFitnessExtension, opts ...grpc.CallOption) (*RegistrationResult, error)
	// GetDhammaContext retrieves a scored Dhamma reflection for a given data context.
	// Used by the Translucent Gate to annotate proposals with ethical weighting.
	GetDhammaContext(ctx context.Context, in *DataContext, opts ...grpc.CallOption) (*ReflectionResult, error)
	// WriteAnalystBriefing writes a briefing packet to analyst-inbox/.
	// Called by AntiGravity when it has completed a phase and needs review.
	WriteAnalystBriefing(ctx context.Context, in *Briefing, opts ...grpc.CallOption) (*OperationStatus, error)
	// ReadAnalystVerdict reads the latest verdict for a given topic or proposal.
	// Called by AntiGravity to check if a verdict has been issued.
	ReadAnalystVerdict(ctx context.Context, in *VerdictQuery, opts ...grpc.CallOption) (*AnalystVerdict, error)
	// ReportMetrics submits domain-specific metric values to the global fitness vector.
	// Called periodically by factories after their internal collection loops.
	ReportMetrics(ctx context.Context, in *MetricReport, opts ...grpc.CallOption) (*OperationStatus, error)
	// CreateAssemblyLine initiates a new software service assembly line from a spec.
	CreateAssemblyLine(ctx context.Context, in *SpecDocument, opts ...grpc.CallOption) (*AssemblyLine, error)
	// GetAssemblyLineStatus returns the current lifecycle state of an assembly line.
	GetAssemblyLineStatus(ctx context.Context, in *AssemblyLineID, opts ...grpc.CallOption) (*LifecycleStatus, error)
	// AdvanceLifecycle transitions an assembly line to the next state.
	// Enforces state-machine gates (INTAKE → DESIGN → SCAFFOLD → BUILD → VERIFY → DELIVERED).
	AdvanceLifecycle(ctx context.Context, in *LifecycleAdvance, opts ...grpc.CallOption) (*LifecycleStatus, error)
	// UpdateSkill proposes a new version of an agent's skill.
	// Must pass Safety Rail. Returns a MerkleProof on success.
	UpdateSkill(ctx context.Context, in *SkillUpdateRequest, opts ...grpc.CallOption) (*MerkleProof, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) CreateFactory(ctx context.Context, in *FactoryRequest, opts ...grpc.CallOption) (*FactoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryResponse)
	err := c.cc.Invoke(ctx, Orchestrator_CreateFactory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StopFactory(ctx context.Context, in *FactoryID, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, Orchestrator_StopFactory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ListFactories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FactoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryList)
	err := c.cc.Invoke(ctx, Orchestrator_ListFactories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) SubmitProposal(ctx context.Context, in *ActionProposal, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VerificationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_SubmitProposal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionProposal, VerificationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_SubmitProposalClient = grpc.ServerStreamingClient[VerificationEvent]

func (c *orchestratorClient) ApproveAction(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*MerkleProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleProof)
	err := c.cc.Invoke(ctx, Orchestrator_ApproveAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) VetoAction(ctx context.Context, in *VetoRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, Orchestrator_VetoAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetFitnessSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FitnessSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FitnessSnapshot)
	err := c.cc.Invoke(ctx, Orchestrator_GetFitnessSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) RegisterDomainMetrics(ctx context.Context, in *DomainFitnessExtension, opts ...grpc.CallOption) (*RegistrationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResult)
	err := c.cc.Invoke(ctx, Orchestrator_RegisterDomainMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetDhammaContext(ctx context.Context, in *DataContext, opts ...grpc.CallOption) (*ReflectionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReflectionResult)
	err := c.cc.Invoke(ctx, Orchestrator_GetDhammaContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) WriteAnalystBriefing(ctx context.Context, in *Briefing, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, Orchestrator_WriteAnalystBriefing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ReadAnalystVerdict(ctx context.Context, in *VerdictQuery, opts ...grpc.CallOption) (*AnalystVerdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalystVerdict)
	err := c.cc.Invoke(ctx, Orchestrator_ReadAnalystVerdict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ReportMetrics(ctx context.Context, in *MetricReport, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, Orchestrator_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) CreateAssemblyLine(ctx context.Context, in *SpecDocument, opts ...grpc.CallOption) (*AssemblyLine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssemblyLine)
	err := c.cc.Invoke(ctx, Orchestrator_CreateAssemblyLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetAssemblyLineStatus(ctx context.Context, in *AssemblyLineID, opts ...grpc.CallOption) (*LifecycleStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifecycleStatus)
	err := c.cc.Invoke(ctx, Orchestrator_GetAssemblyLineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) AdvanceLifecycle(ctx context.Context, in *LifecycleAdvance, opts ...grpc.CallOption) (*LifecycleStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifecycleStatus)
	err := c.cc.Invoke(ctx, Orchestrator_AdvanceLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) UpdateSkill(ctx context.Context, in *SkillUpdateRequest, opts ...grpc.CallOption) (*MerkleProof, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerkleProof)
	err := c.cc.Invoke(ctx, Orchestrator_UpdateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
//
// Orchestrator is the central control plane for Sati-Central.
// It manages factory lifecycles, the safety verification pipeline,
// the fitness vector, Dhamma context retrieval, and the analyst interface.
type OrchestratorServer interface {
	// CreateFactory instantiates and registers a new agent factory.
	// Returns the factory ID and initial fitness baseline.
	CreateFactory(context.Context, *FactoryRequest) (*FactoryResponse, error)
	// StopFactory gracefully shuts down a running factory.
	// Waits for in-flight proposals to complete before stopping.
	StopFactory(context.Context, *FactoryID) (*OperationStatus, error)
	// ListFactories returns all registered factories and their current status.
	ListFactories(context.Context, *Empty) (*FactoryList, error)
	// SubmitProposal submits an ActionProposal for safety verification.
	// Returns a stream of VerificationEvents as the proposal progresses
	// through: received → verifying → verdict → [gate_pending] → committed/vetoed.
	SubmitProposal(*ActionProposal, grpc.ServerStreamingServer[VerificationEvent]) error
	// ApproveAction signs a Translucent Gate approval for a security-adjacent proposal.
	// Requires a valid ApprovalSignature. Returns a MerkleProof for the committed leaf.
	ApproveAction(context.Context, *ApprovalRequest) (*MerkleProof, error)
	// VetoAction issues a veto on a pending proposal.
	// May be called by the Analyst Droid or the human operator.
	VetoAction(context.Context, *VetoRequest) (*OperationStatus, error)
	// GetFitnessSnapshot returns the current global fitness vector state.
	// Equivalent to reading otel-snapshots/latest.json but via RPC.
	GetFitnessSnapshot(context.Context, *Empty) (*FitnessSnapshot, error)
	// RegisterDomainMetrics registers domain-specific fitness metric extensions.
	// Called by factories at startup to advertise their domain metrics.
	RegisterDomainMetrics(context.Context, *DomainFitnessExtension) (*RegistrationResult, error)
	// GetDhammaContext retrieves a scored Dhamma reflection for a given data context.
	// Used by the Translucent Gate to annotate proposals with ethical weighting.
	GetDhammaContext(context.Context, *DataContext) (*ReflectionResult, error)
	// WriteAnalystBriefing writes a briefing packet to analyst-inbox/.
	// Called by AntiGravity when it has completed a phase and needs review.
	WriteAnalystBriefing(context.Context, *Briefing) (*OperationStatus, error)
	// ReadAnalystVerdict reads the latest verdict for a given topic or proposal.
	// Called by AntiGravity to check if a verdict has been issued.
	ReadAnalystVerdict(context.Context, *VerdictQuery) (*AnalystVerdict, error)
	// ReportMetrics submits domain-specific metric values to the global fitness vector.
	// Called periodically by factories after their internal collection loops.
	ReportMetrics(context.Context, *MetricReport) (*OperationStatus, error)
	// CreateAssemblyLine initiates a new software service assembly line from a spec.
	CreateAssemblyLine(context.Context, *SpecDocument) (*AssemblyLine, error)
	// GetAssemblyLineStatus returns the current lifecycle state of an assembly line.
	GetAssemblyLineStatus(context.Context, *AssemblyLineID) (*LifecycleStatus, error)
	// AdvanceLifecycle transitions an assembly line to the next state.
	// Enforces state-machine gates (INTAKE → DESIGN → SCAFFOLD → BUILD → VERIFY → DELIVERED).
	AdvanceLifecycle(context.Context, *LifecycleAdvance) (*LifecycleStatus, error)
	// UpdateSkill proposes a new version of an agent's skill.
	// Must pass Safety Rail. Returns a MerkleProof on success.
	UpdateSkill(context.Context, *SkillUpdateRequest) (*MerkleProof, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) CreateFactory(context.Context, *FactoryRequest) (*FactoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFactory not implemented")
}
func (UnimplementedOrchestratorServer) StopFactory(context.Context, *FactoryID) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopFactory not implemented")
}
func (UnimplementedOrchestratorServer) ListFactories(context.Context, *Empty) (*FactoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFactories not implemented")
}
func (UnimplementedOrchestratorServer) SubmitProposal(*ActionProposal, grpc.ServerStreamingServer[VerificationEvent]) error {
	return status.Error(codes.Unimplemented, "method SubmitProposal not implemented")
}
func (UnimplementedOrchestratorServer) ApproveAction(context.Context, *ApprovalRequest) (*MerkleProof, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAction not implemented")
}
func (UnimplementedOrchestratorServer) VetoAction(context.Context, *VetoRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method VetoAction not implemented")
}
func (UnimplementedOrchestratorServer) GetFitnessSnapshot(context.Context, *Empty) (*FitnessSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFitnessSnapshot not implemented")
}
func (UnimplementedOrchestratorServer) RegisterDomainMetrics(context.Context, *DomainFitnessExtension) (*RegistrationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDomainMetrics not implemented")
}
func (UnimplementedOrchestratorServer) GetDhammaContext(context.Context, *DataContext) (*ReflectionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDhammaContext not implemented")
}
func (UnimplementedOrchestratorServer) WriteAnalystBriefing(context.Context, *Briefing) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAnalystBriefing not implemented")
}
func (UnimplementedOrchestratorServer) ReadAnalystVerdict(context.Context, *VerdictQuery) (*AnalystVerdict, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAnalystVerdict not implemented")
}
func (UnimplementedOrchestratorServer) ReportMetrics(context.Context, *MetricReport) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedOrchestratorServer) CreateAssemblyLine(context.Context, *SpecDocument) (*AssemblyLine, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssemblyLine not implemented")
}
func (UnimplementedOrchestratorServer) GetAssemblyLineStatus(context.Context, *AssemblyLineID) (*LifecycleStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssemblyLineStatus not implemented")
}
func (UnimplementedOrchestratorServer) AdvanceLifecycle(context.Context, *LifecycleAdvance) (*LifecycleStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceLifecycle not implemented")
}
func (UnimplementedOrchestratorServer) UpdateSkill(context.Context, *SkillUpdateRequest) (*MerkleProof, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_CreateFactory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateFactory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateFactory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateFactory(ctx, req.(*FactoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StopFactory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StopFactory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_StopFactory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StopFactory(ctx, req.(*FactoryID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ListFactories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListFactories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListFactories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListFactories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_SubmitProposal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionProposal)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).SubmitProposal(m, &grpc.GenericServerStream[ActionProposal, VerificationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_SubmitProposalServer = grpc.ServerStreamingServer[VerificationEvent]

func _Orchestrator_ApproveAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ApproveAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ApproveAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ApproveAction(ctx, req.(*ApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_VetoAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VetoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).VetoAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_VetoAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).VetoAction(ctx, req.(*VetoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetFitnessSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetFitnessSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetFitnessSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetFitnessSnapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_RegisterDomainMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainFitnessExtension)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RegisterDomainMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_RegisterDomainMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RegisterDomainMetrics(ctx, req.(*DomainFitnessExtension))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetDhammaContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetDhammaContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetDhammaContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetDhammaContext(ctx, req.(*DataContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_WriteAnalystBriefing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Briefing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).WriteAnalystBriefing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_WriteAnalystBriefing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).WriteAnalystBriefing(ctx, req.(*Briefing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ReadAnalystVerdict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerdictQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ReadAnalystVerdict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ReadAnalystVerdict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ReadAnalystVerdict(ctx, req.(*VerdictQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ReportMetrics(ctx, req.(*MetricReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_CreateAssemblyLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpecDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateAssemblyLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateAssemblyLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateAssemblyLine(ctx, req.(*SpecDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetAssemblyLineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssemblyLineID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetAssemblyLineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetAssemblyLineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetAssemblyLineStatus(ctx, req.(*AssemblyLineID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_AdvanceLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifecycleAdvance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).AdvanceLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_AdvanceLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).AdvanceLifecycle(ctx, req.(*LifecycleAdvance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).UpdateSkill(ctx, req.(*SkillUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sati.central.v1.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFactory",
			Handler:    _Orchestrator_CreateFactory_Handler,
		},
		{
			MethodName: "StopFactory",
			Handler:    _Orchestrator_StopFactory_Handler,
		},
		{
			MethodName: "ListFactories",
			Handler:    _Orchestrator_ListFactories_Handler,
		},
		{
			MethodName: "ApproveAction",
			Handler:    _Orchestrator_ApproveAction_Handler,
		},
		{
			MethodName: "VetoAction",
			Handler:    _Orchestrator_VetoAction_Handler,
		},
		{
			MethodName: "GetFitnessSnapshot",
			Handler:    _Orchestrator_GetFitnessSnapshot_Handler,
		},
		{
			MethodName: "RegisterDomainMetrics",
			Handler:    _Orchestrator_RegisterDomainMetrics_Handler,
		},
		{
			MethodName: "GetDhammaContext",
			Handler:    _Orchestrator_GetDhammaContext_Handler,
		},
		{
			MethodName: "WriteAnalystBriefing",
			Handler:    _Orchestrator_WriteAnalystBriefing_Handler,
		},
		{
			MethodName: "ReadAnalystVerdict",
			Handler:    _Orchestrator_ReadAnalystVerdict_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _Orchestrator_ReportMetrics_Handler,
		},
		{
			MethodName: "CreateAssemblyLine",
			Handler:    _Orchestrator_CreateAssemblyLine_Handler,
		},
		{
			MethodName: "GetAssemblyLineStatus",
			Handler:    _Orchestrator_GetAssemblyLineStatus_Handler,
		},
		{
			MethodName: "AdvanceLifecycle",
			Handler:    _Orchestrator_AdvanceLifecycle_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _Orchestrator_UpdateSkill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubmitProposal",
			Handler:       _Orchestrator_SubmitProposal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/orchestrator.proto",
}
