/**
 * @fileoverview gRPC-Web generated client stub for sati.central.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v7.34.1
// source: orchestrator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as orchestrator_pb from './orchestrator_pb'; // proto import: "orchestrator.proto"


export class OrchestratorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateFactory = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/CreateFactory',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.FactoryRequest,
    orchestrator_pb.FactoryResponse,
    (request: orchestrator_pb.FactoryRequest) => {
      return request.serializeBinary();
    },
    orchestrator_pb.FactoryResponse.deserializeBinary
  );

  createFactory(
    request: orchestrator_pb.FactoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.FactoryResponse>;

  createFactory(
    request: orchestrator_pb.FactoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FactoryResponse) => void): grpcWeb.ClientReadableStream<orchestrator_pb.FactoryResponse>;

  createFactory(
    request: orchestrator_pb.FactoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FactoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/CreateFactory',
        request,
        metadata || {},
        this.methodDescriptorCreateFactory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/CreateFactory',
    request,
    metadata || {},
    this.methodDescriptorCreateFactory);
  }

  methodDescriptorStopFactory = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/StopFactory',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.FactoryID,
    orchestrator_pb.OperationStatus,
    (request: orchestrator_pb.FactoryID) => {
      return request.serializeBinary();
    },
    orchestrator_pb.OperationStatus.deserializeBinary
  );

  stopFactory(
    request: orchestrator_pb.FactoryID,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.OperationStatus>;

  stopFactory(
    request: orchestrator_pb.FactoryID,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void): grpcWeb.ClientReadableStream<orchestrator_pb.OperationStatus>;

  stopFactory(
    request: orchestrator_pb.FactoryID,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/StopFactory',
        request,
        metadata || {},
        this.methodDescriptorStopFactory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/StopFactory',
    request,
    metadata || {},
    this.methodDescriptorStopFactory);
  }

  methodDescriptorListFactories = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/ListFactories',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.Empty,
    orchestrator_pb.FactoryList,
    (request: orchestrator_pb.Empty) => {
      return request.serializeBinary();
    },
    orchestrator_pb.FactoryList.deserializeBinary
  );

  listFactories(
    request: orchestrator_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.FactoryList>;

  listFactories(
    request: orchestrator_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FactoryList) => void): grpcWeb.ClientReadableStream<orchestrator_pb.FactoryList>;

  listFactories(
    request: orchestrator_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FactoryList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/ListFactories',
        request,
        metadata || {},
        this.methodDescriptorListFactories,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/ListFactories',
    request,
    metadata || {},
    this.methodDescriptorListFactories);
  }

  methodDescriptorSubmitProposal = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/SubmitProposal',
    grpcWeb.MethodType.SERVER_STREAMING,
    orchestrator_pb.ActionProposal,
    orchestrator_pb.VerificationEvent,
    (request: orchestrator_pb.ActionProposal) => {
      return request.serializeBinary();
    },
    orchestrator_pb.VerificationEvent.deserializeBinary
  );

  submitProposal(
    request: orchestrator_pb.ActionProposal,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<orchestrator_pb.VerificationEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/sati.central.v1.Orchestrator/SubmitProposal',
      request,
      metadata || {},
      this.methodDescriptorSubmitProposal);
  }

  methodDescriptorApproveAction = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/ApproveAction',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.ApprovalRequest,
    orchestrator_pb.MerkleProof,
    (request: orchestrator_pb.ApprovalRequest) => {
      return request.serializeBinary();
    },
    orchestrator_pb.MerkleProof.deserializeBinary
  );

  approveAction(
    request: orchestrator_pb.ApprovalRequest,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.MerkleProof>;

  approveAction(
    request: orchestrator_pb.ApprovalRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.MerkleProof) => void): grpcWeb.ClientReadableStream<orchestrator_pb.MerkleProof>;

  approveAction(
    request: orchestrator_pb.ApprovalRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.MerkleProof) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/ApproveAction',
        request,
        metadata || {},
        this.methodDescriptorApproveAction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/ApproveAction',
    request,
    metadata || {},
    this.methodDescriptorApproveAction);
  }

  methodDescriptorVetoAction = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/VetoAction',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.VetoRequest,
    orchestrator_pb.OperationStatus,
    (request: orchestrator_pb.VetoRequest) => {
      return request.serializeBinary();
    },
    orchestrator_pb.OperationStatus.deserializeBinary
  );

  vetoAction(
    request: orchestrator_pb.VetoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.OperationStatus>;

  vetoAction(
    request: orchestrator_pb.VetoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void): grpcWeb.ClientReadableStream<orchestrator_pb.OperationStatus>;

  vetoAction(
    request: orchestrator_pb.VetoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/VetoAction',
        request,
        metadata || {},
        this.methodDescriptorVetoAction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/VetoAction',
    request,
    metadata || {},
    this.methodDescriptorVetoAction);
  }

  methodDescriptorGetFitnessSnapshot = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/GetFitnessSnapshot',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.Empty,
    orchestrator_pb.FitnessSnapshot,
    (request: orchestrator_pb.Empty) => {
      return request.serializeBinary();
    },
    orchestrator_pb.FitnessSnapshot.deserializeBinary
  );

  getFitnessSnapshot(
    request: orchestrator_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.FitnessSnapshot>;

  getFitnessSnapshot(
    request: orchestrator_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FitnessSnapshot) => void): grpcWeb.ClientReadableStream<orchestrator_pb.FitnessSnapshot>;

  getFitnessSnapshot(
    request: orchestrator_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.FitnessSnapshot) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/GetFitnessSnapshot',
        request,
        metadata || {},
        this.methodDescriptorGetFitnessSnapshot,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/GetFitnessSnapshot',
    request,
    metadata || {},
    this.methodDescriptorGetFitnessSnapshot);
  }

  methodDescriptorRegisterDomainMetrics = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/RegisterDomainMetrics',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.DomainFitnessExtension,
    orchestrator_pb.RegistrationResult,
    (request: orchestrator_pb.DomainFitnessExtension) => {
      return request.serializeBinary();
    },
    orchestrator_pb.RegistrationResult.deserializeBinary
  );

  registerDomainMetrics(
    request: orchestrator_pb.DomainFitnessExtension,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.RegistrationResult>;

  registerDomainMetrics(
    request: orchestrator_pb.DomainFitnessExtension,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.RegistrationResult) => void): grpcWeb.ClientReadableStream<orchestrator_pb.RegistrationResult>;

  registerDomainMetrics(
    request: orchestrator_pb.DomainFitnessExtension,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.RegistrationResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/RegisterDomainMetrics',
        request,
        metadata || {},
        this.methodDescriptorRegisterDomainMetrics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/RegisterDomainMetrics',
    request,
    metadata || {},
    this.methodDescriptorRegisterDomainMetrics);
  }

  methodDescriptorGetDhammaContext = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/GetDhammaContext',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.DataContext,
    orchestrator_pb.ReflectionResult,
    (request: orchestrator_pb.DataContext) => {
      return request.serializeBinary();
    },
    orchestrator_pb.ReflectionResult.deserializeBinary
  );

  getDhammaContext(
    request: orchestrator_pb.DataContext,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.ReflectionResult>;

  getDhammaContext(
    request: orchestrator_pb.DataContext,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.ReflectionResult) => void): grpcWeb.ClientReadableStream<orchestrator_pb.ReflectionResult>;

  getDhammaContext(
    request: orchestrator_pb.DataContext,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.ReflectionResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/GetDhammaContext',
        request,
        metadata || {},
        this.methodDescriptorGetDhammaContext,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/GetDhammaContext',
    request,
    metadata || {},
    this.methodDescriptorGetDhammaContext);
  }

  methodDescriptorWriteAnalystBriefing = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/WriteAnalystBriefing',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.Briefing,
    orchestrator_pb.OperationStatus,
    (request: orchestrator_pb.Briefing) => {
      return request.serializeBinary();
    },
    orchestrator_pb.OperationStatus.deserializeBinary
  );

  writeAnalystBriefing(
    request: orchestrator_pb.Briefing,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.OperationStatus>;

  writeAnalystBriefing(
    request: orchestrator_pb.Briefing,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void): grpcWeb.ClientReadableStream<orchestrator_pb.OperationStatus>;

  writeAnalystBriefing(
    request: orchestrator_pb.Briefing,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.OperationStatus) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/WriteAnalystBriefing',
        request,
        metadata || {},
        this.methodDescriptorWriteAnalystBriefing,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/WriteAnalystBriefing',
    request,
    metadata || {},
    this.methodDescriptorWriteAnalystBriefing);
  }

  methodDescriptorReadAnalystVerdict = new grpcWeb.MethodDescriptor(
    '/sati.central.v1.Orchestrator/ReadAnalystVerdict',
    grpcWeb.MethodType.UNARY,
    orchestrator_pb.VerdictQuery,
    orchestrator_pb.AnalystVerdict,
    (request: orchestrator_pb.VerdictQuery) => {
      return request.serializeBinary();
    },
    orchestrator_pb.AnalystVerdict.deserializeBinary
  );

  readAnalystVerdict(
    request: orchestrator_pb.VerdictQuery,
    metadata?: grpcWeb.Metadata | null): Promise<orchestrator_pb.AnalystVerdict>;

  readAnalystVerdict(
    request: orchestrator_pb.VerdictQuery,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: orchestrator_pb.AnalystVerdict) => void): grpcWeb.ClientReadableStream<orchestrator_pb.AnalystVerdict>;

  readAnalystVerdict(
    request: orchestrator_pb.VerdictQuery,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: orchestrator_pb.AnalystVerdict) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sati.central.v1.Orchestrator/ReadAnalystVerdict',
        request,
        metadata || {},
        this.methodDescriptorReadAnalystVerdict,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sati.central.v1.Orchestrator/ReadAnalystVerdict',
    request,
    metadata || {},
    this.methodDescriptorReadAnalystVerdict);
  }

}

